version: '3.1'

services:
    cron:
        build:
            context: ../
            dockerfile: Dockerfile
        container_name: cron
        environment:
            - TZ=UCT
            - TESTING=0